# Docker Compose override for complete offline mode
# Usage: docker-compose -f docker-compose.offline.yml -f docker-compose.offline-override.yml up

version: '3.8'

services:
  cockpit-frontend:
    environment:
      # Override API URL for offline testing
      - COCKPIT_API_URL=http://localhost:8000
      - COCKPIT_DEBUG=true  # Enable debug for offline testing
    networks:
      cockpit-network:
        aliases:
          - frontend.local
    # Remove external dependencies
    external_links: []
    
  cockpit-backend:
    environment:
      # Mock Nautobot for offline testing
      - NAUTOBOT_HOST=http://mock-nautobot:8080
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    networks:
      cockpit-network:
        aliases:
          - backend.local

  # Mock Nautobot service for complete offline testing
  mock-nautobot:
    image: mockserver/mockserver:latest
    container_name: mock-nautobot
    ports:
      - "8080:1080"
    environment:
      - MOCKSERVER_SERVER_PORT=1080
      - MOCKSERVER_LOG_LEVEL=INFO
    volumes:
      - ./docker/mock-expectations.json:/config/expectations.json:ro
    networks:
      cockpit-network:
        aliases:
          - nautobot.local
    restart: unless-stopped
    profiles:
      - "offline-testing"

networks:
  cockpit-network:
    external: false
    internal: true  # No external network access
