version: '3.8'

services:
  frontend:
    build: .
    container_name: cockpit-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    volumes:
      - ./src:/app/src:ro
      - ./production:/app/production:ro
      - ./package.json:/app/package.json:ro
      - ./vite.config.js:/app/vite.config.js:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: cockpit-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      # Server Configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - DEBUG=false
      
      # Nautobot Configuration (REQUIRED - Set these values)
      - NAUTOBOT_HOST=${NAUTOBOT_HOST:-http://localhost:8080}
      - NAUTOBOT_TOKEN=${NAUTOBOT_TOKEN:-your-nautobot-token-here}
      - NAUTOBOT_TIMEOUT=${NAUTOBOT_TIMEOUT:-30}
      
      # Authentication Configuration (REQUIRED - Change in production)
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      
      # CORS Configuration
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS:-true}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/docs')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    name: nautobot_backend
    external: true
