version: '3.8'

services:
  cockpit:
    build:
      context: .
      dockerfile: Dockerfile.unified.production
    container_name: cockpit-unified-production
    restart: unless-stopped
    ports:
      - "3000:3000"  # Frontend port
      - "8000:8000"  # Backend port
    networks:
      - backend
    environment:
      # Node.js Frontend Configuration
      - NODE_ENV=production
      
      # Backend Server Configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - DEBUG=false
      
      # Nautobot Configuration (REQUIRED - Set these values)
      - NAUTOBOT_HOST=${NAUTOBOT_HOST}
      - NAUTOBOT_TOKEN=${NAUTOBOT_TOKEN}
      - NAUTOBOT_TIMEOUT=${NAUTOBOT_TIMEOUT:-30}
      
      # Authentication Configuration (REQUIRED - Change in production)
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      
      # CORS Configuration
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS:-true}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      # Persistent database storage (read-write)
      - ./data/settings:/app/backend/settings
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:3000/ && curl -f http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    name: nautobot_backend
    external: true
